/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nuzuwvgkpngerbudynao"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51enV3dmdrcG5nZXJidWR5bmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NTgwMjAsImV4cCI6MjA3OTUzNDAyMH0.aahZIZwD9phArVlyMNQgj5b-ahGv4IuC-4osF8gaWJU"